export { default as cacheImgs } from './cacheImgs'
export { default as delay } from './delay'
export { default as getErrorMessage } from './getErrorMessage'
export { default as isEmailValid } from './isEmailValid'
export { default as isTelValid } from './isTelValid'
